### PR TITLE
Upgrades to Java Client to 2.5.1, adds RBAC support through config

### PR DESCRIPTION
**Pull request by etspaceman**
@mathieuancelin let me know what you think about this. My company plans to use Couchbase 5 and I'd love to get this working. 

The majority of the change has to do with authentication. This has backwards compatibility with Couchbase 4 as it continues to support Bucket Password auth. However, Couchbase dropped support for this in Couchbase 5. To accommodate this, I did the following:

- Added a ClusterAuth case class containing a username/password
- Added an optional clusterAuth property to the BucketConfig
- Added support for reading cluster authentication properties via an "authentication" section in the bucket config. 
- Added support for running the integration test against Couchbase 5 or 4 using an environment variable of USE_RBAC (defaulted to false, meaning the current Couchbase 4 setup is the default). Note that this assumes a user/pass of Administrator/Administrator. I could set these against env. vars as well but considering you had already made some assumptions in the initial integration test, I figured this would be safe. 

I'd like to know what your thoughts are ASAP so that we can start to leverage this newest setup. Let me know if you're looking to change any of this approach, happy to implement adjustments as needed. 

Thanks!

### CODE REVIEW

**Comment by mathieuancelin** [comment]
Hi @etspaceman I'm pretty good with all this.

I'll merge the PR and maybe add a generic way to be able to configure the couchbase cluster.

I guess you need a new stable version of reactivecouchbase with those changes ?

**Comment by etspaceman** [comment]
Yes! That would be great! Thanks so much for the quick review @mathieuancelin 🥇

**Comment by mathieuancelin** [comment]
@etspaceman new binaries are available, it's a 1.1.0

**Comment by etspaceman** [comment]
Thanks @mathieuancelin ! I'm using it and its working great.

**Pull request merged**
