### PR TITLE
Circe support

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by etspaceman** [comment]
`eric@singlecomm:~/reactivecouchbase-rs-core$ export USE_RBAC=true && sbt test
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /home/eric/.sbt/1.0/plugins
[info] Loading project definition from /home/eric/reactivecouchbase-rs-core/project
[info] Loading settings from build.sbt ...
[info] Set current project to reactivecouchbase-rs-core (in build file:/home/eric/reactivecouchbase-rs-core/)
[info] Compiling 3 Scala sources to /home/eric/reactivecouchbase-rs-core/target/scala-2.12/test-classes ...
[info] Done compiling.
good
bad
bad
bad
bad
Mar 06, 2018 5:00:54 PM com.couchbase.client.core.CouchbaseCore <init>
INFO: CouchbaseEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslTruststoreFile='null', sslKeystorePassword=false, sslTruststorePassword=false, sslKeystore=null, sslTruststore=null, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=4, computationPoolSize=4, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=12, queryServiceEndpoints=12, searchServiceEndpoints=12, configPollInterval=2500, configPollFloorInterval=50, ioPool=NioEventLoopGroup, kvIoPool=null, viewIoPool=null, searchIoPool=null, queryIoPool=null, coreScheduler=CoreScheduler, memcachedHashingStrategy=DefaultMemcachedHashingStrategy, eventBus=DefaultEventBus, packageNameAndVersion=couchbase-java-client/2.5.5 (git: 2.5.5, core: 1.5.5), retryStrategy=BestEffort, maxRequestLifetime=75000, retryDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=100, upper=100000}, reconnectDelay=ExponentialDelay{growBy 1.0 MILLISECONDS, powers of 2; lower=32, upper=4096}, observeIntervalDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=10, upper=100000}, keepAliveInterval=30000, continuousKeepAliveEnabled=true, keepAliveErrorThreshold=4, keepAliveTimeout=2500, autoreleaseAfter=2000, bufferPoolingEnabled=true, tcpNodelayEnabled=true, mutationTokensEnabled=false, socketConnectTimeout=1000, callbacksOnIoPool=false, disconnectTimeout=25000, requestBufferWaitStrategy=com.couchbase.client.core.env.DefaultCoreEnvironment$2@4d8bdf0c, certAuthEnabled=false, coreSendHook=null, forceSaslPlain=false, queryTimeout=75000, viewTimeout=75000, searchTimeout=75000, analyticsTimeout=75000, kvTimeout=2500, connectTimeout=5000, dnsSrvEnabled=false}
Mar 06, 2018 5:00:55 PM com.couchbase.client.core.node.CouchbaseNode signalConnected
INFO: Connected to Node 127.0.0.1/localhost
Mar 06, 2018 5:00:55 PM com.couchbase.client.core.config.DefaultConfigurationProvider$8 call
INFO: Opened bucket default
[info] RetriesTest:
[info] Retries
[info] - should not retry when passing a good computation
[info] Retries
[info] - should fail after max retries when passing a bad computation
Remove1: {}
Remove2: {}
Remove3: {}
Insert1: {
  "message" : "Hello World",
  "type" : "doc"
}
Insert2: {
  "message" : "Goodbye World",
  "type" : "doc"
}
maybeDoc1: Some({"message":"Hello World","type":"doc"})
maybeDoc1AsClass: Some(TestModel(Hello World,Some(doc)))
maybeDoc1AsClass2: Some(TestModel2(Hello World,Some(doc)))
maybeDoc2: Some({"message":"Goodbye World","type":"doc"})
maybeDoc3: None
doc1Exists: true
doc2Exists: true
results1: Vector({"message":"Hello World"}, {"message":"Goodbye World"})
resultsAsClass: Vector(TestModel(Hello World,None), TestModel(Goodbye World,None))
resultsAsClass2: Vector(TestModel2(Hello World,None), TestModel2(Goodbye World,None))
results2: Vector({"message":"Hello World"})
results3: Vector({"message":"Hello World"}, {"message":"Goodbye World"})
results4: Vector({"message":"Hello World"}, {"message":"Goodbye World"})
results5: Vector(HELLO WORLD, GOODBYE WORLD)
counter1: 1
counter2: 2
counter3: 3
counter4: 2
counter5: 2
found item 2 : {
  "date" : 387006535418,
  "message" : "message nb 1"
}
found item 1 : {
  "date" : 387006535418,
  "message" : "message nb 1"
}
found item 1 : {
  "date" : 387325074440,
  "message" : "message nb 2"
}
found item 2 : {
  "date" : 387325074440,
  "message" : "message nb 2"
}
found item 2 : {
  "date" : 387647707281,
  "message" : "message nb 3"
}
found item 1 : {
  "date" : 387647707281,
  "message" : "message nb 3"
}
found item 2 : {
  "date" : 387965349527,
  "message" : "message nb 4"
}
found item 1 : {
  "date" : 387965349527,
  "message" : "message nb 4"
}
found item 1 : {
  "date" : 388286561902,
  "message" : "message nb 5"
}
found item 2 : {
  "date" : 388286561902,
  "message" : "message nb 5"
}
done 2
Res: Vector({"type":"timedoc","message":"message nb 1","date":387006535418}, {"type":"timedoc","message":"message nb 2","date":387325074440}, {"type":"timedoc","message":"message nb 3","date":387647707281}, {"type":"timedoc","message":"message nb 4","date":387965349527}, {"type":"timedoc","message":"message nb 5","date":388286561902}, {"type":"timedoc","message":"message nb 6","date":388607121643})
done 1
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.config.DefaultConfigurationProvider$11 call
INFO: Closed bucket default
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.node.CouchbaseNode signalDisconnected
INFO: Disconnected from Node 127.0.0.1/localhost
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown IoPool: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown kvIoPool: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown viewIoPool: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown Netty: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown queryIoPool: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown searchIoPool: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown Core Scheduler: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown Runtime Metrics Collector: success 
Mar 06, 2018 5:01:03 PM com.couchbase.client.core.env.DefaultCoreEnvironment$6 call
INFO: Shutdown Latency Metrics Collector: success 
[info] BasicReactiveCouchbaseSpec:
[info] ReactiveCouchbase ReactiveStreams Edition
[info] - should work
[info] Run completed in 10 seconds, 659 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 3, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 20 s, completed Mar 6, 2018 5:01:03 PM
`

**Comment by etspaceman** [comment]
@mathieuancelin This is ready for review

**Comment by mathieuancelin** [comment]
This is awesome @etspaceman, I love Circe :D 

I'll do the review asap !

**Comment by mathieuancelin** [comment]
Hey @etspaceman, the PR has been merged and I took some time to cleanup the repo, add a release process, pushed releases on bintray and jcenter, etc ...

In the future, I think I will split the project in modules likes

* reactivecouchbase-rs-core
* reactivecouchbase-rs-play-json
* reactivecouchbase-rs-circe
* reactivecouchbase-rs-*

wdyt ?

**Comment by etspaceman** [comment]
I love that idea!

**Pull request merged**
